<a href="https://colab.research.google.com/github/sireesha733/-sum-product-and-dict-with-single-input-problem-sum-of-natural-numbers-and-factorial-numbers/blob/main/python_statistics_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import statistics
print(statistics.pstdev([1,3,5,7,9,11]))
print(statistics.pstdev([2,2.5,1.25,3.1,1.75,2.8]))
print(statistics.pstdev([-11,5.5, -3.4,7.1]))
print(statistics.pstdev([1,30,50,100]))

3.415650255319866
0.6322358912796886
7.287146217827662
36.09276243237694


In [ ]:
# Import statistics Library
import statistics

# Calculate the standard deviation from a sample of data
print(statistics.stdev([1, 3, 5, 7, 9, 11]))
print(statistics.stdev([2, 2.5, 1.25, 3.1, 1.75, 2.8]))
print(statistics.stdev([-11, 5.5, -3.4, 7.1]))
print(statistics.stdev([1, 30, 50, 100]))


3.7416573867739413
0.6925797186365383
8.414471660973927
41.67633221226008


In [ ]:
# Import statistics Library
import statistics

# Calculate the variance of an entire population
print(statistics.pvariance([1, 3, 5, 7, 9, 11]))
print(statistics.pvariance([2, 2.5, 1.25, 3.1, 1.75, 2.8]))
print(statistics.pvariance([-11, 5.5, -3.4, 7.1]))
print(statistics.pvariance([1, 30, 50, 100]))


11.666666666666666
0.3997222222222222
53.1025
1302.6875


In [ ]:
# Import statistics Library
import statistics

# Calculate the variance from a sample of data
print(statistics.variance([1, 3, 5, 7, 9, 11]))
print(statistics.variance([2, 2.5, 1.25, 3.1, 1.75, 2.8]))
print(statistics.variance([-11, 5.5, -3.4, 7.1]))
print(statistics.variance([1, 30, 50, 100]))


14
0.47966666666666663
70.80333333333333
1736.9166666666667


In [ ]:
import pandas as pd
df=pd.read_csv("/content/ml.csv")
df.fillna(130,inplace=True)
print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [ ]:
import math
print(math.ceil(1.4))
print(math.ceil(5.3))
print(math.ceil(-5.3))
print(math.ceil(22.))
print(math.ceil(10.0))


2
6
-5
22
10


In [ ]:
import math
print(math.factorial(9))
print(math.factorial(6))
print(math.factorial(12))

362880
720
479001600


In [ ]:
import math
print(math.floor(0.6))
print(math.floor(1.4))
print(math.floor(5.3))
print(math.floor(-5.3))
print(math.floor(22.6))
print(math.floor(10.0))

0
1
5
-6
22
10


In [ ]:
import math
print (math.gcd(3, 6))
print (math.gcd(6, 12))
print (math.gcd(12, 36))
print (math.gcd(-12, -36))
print (math.gcd(5, 12))
print (math.gcd(10, 0))
print (math.gcd(0, 34))
print (math.gcd(0, 0))

3
6
12
12
1
10
34
0


In [ ]:
import math
print (math.isnan(56))
print (math.isnan(-45.34))
print (math.isnan(+45.34))
print (math.isnan(math.inf))
print (math.isnan(float("nan")))
print (math.isnan(float("inf")))
print (math.isnan(float("-inf")))
print (math.isnan(math.nan))


False
False
False
False
True
False
False
True


In [ ]:
import math
print (math.sqrt(10))
print (math.sqrt(12))
print (math.sqrt(68))
print (math.sqrt(100))
#round square root downward to the nearest integer
print (math.isqrt(10))
print (math.isqrt(12))
print (math.isqrt(68))
print (math.isqrt(100))


3.1622776601683795
3.4641016151377544
8.246211251235321
10.0
3
3
8
10


In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
print("array using numpy",arr)
print("np.version=",np.__version__)
print("type=",type(arr))

array using numpy [1 2 3 4 5]
np.version= 1.23.5
type= <class 'numpy.ndarray'>


In [ ]:
arrtup=np.array((1,2,3,4,5))
print("Array created using tuple datatype",type(arrtup))
a=np.array([42])
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[1,2,3]]])
print("\ndimensions in 0-D arry=",a.ndim)
print("\n0-Dn",a)
print("\ndimensions in 0-D arry=",a.ndim)
print("\n0-Dn",b)
print("\ndimensions in 0-D arry=",a.ndim)
print("\n0-Dn",c)
print("\ndimensions in 0-D arry=",a.ndim)
print("\n0-Dn",d)
print("\nIndexing b[0]=",b[0])
print("\nIndexing of elements using Indexingb b[2]+b[3]=",b[2]+b[3])
print("\narray slicing=",b[0:3])
print("\narray slicing=",b[3:])

Array created using tuple datatype <class 'numpy.ndarray'>

dimensions in 0-D arry= 1

0-Dn [42]

dimensions in 0-D arry= 1

0-Dn [1 2 3 4 5]

dimensions in 0-D arry= 1

0-Dn [[1 2 3]
 [4 5 6]]

dimensions in 0-D arry= 1

0-Dn [[[1 2 3]
  [4 5 6]
  [1 2 3]]]

Indexing b[0]= 1

Indexing of elements using Indexingb b[2]+b[3]= 7

array slicing= [1 2 3]

array slicing= [4 5]


In [ ]:
arrnum=np.array([1,2,3,4])
print(arrnum.dtype)
arralp = np.array(['apple','banana','mango'])
print(arralp.dtype)
x=b.copy()
print("\n x copy of b\n",x)

int64
<U6

 x copy of b
 [1 2 3 4 5]


In [ ]:
from scipy import constants
print(dir(constants))
print(constants.pi)
print(constants.giga)
print(constants.mega)
print(constants.kilo)
print(constants.gram)
print(constants.pound)

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '